# Generated by Django 3.0.5 on 2020-04-23 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('puesto', '0001_initial'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_incorporacion', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('estudios', models.CharField(max_length=30)),
                ('cargo', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='puesto.Puesto')),
                ('persona', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='persona.Persona')),
            ],
        ),
    ]
