# Generated by Django 3.0.5 on 2020-04-23 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('obra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='cliente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='cliente.Cliente'),
        ),
    ]
