# Generated by Django 3.0.5 on 2020-04-23 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electricidad', '0002_prueba1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prueba1',
        ),
    ]
